/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionfuncionarios.vista;

import com.mycompany.gestionfuncionarios.dao.FuncionarioDAOImpl;
import com.mycompany.gestionfuncionarios.dao.IFuncionarioDAO;
import com.mycompany.gestionfuncionarios.modelo.Funcionario;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vitor
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaPrincipal.class.getName());

    /**
     * Creates new form VistaPrincipal
     */
   // Este es el constructor de tu ventana
public VistaPrincipal() {
        initComponents(); // Esta línea la pone NetBeans
        
        // --- CÓDIGO REFACTORIZADO ---
        // Ahora el constructor es limpio.
        // Solo llama al método que carga los datos.
        cargarDatosEnTabla();
        // --- FIN CÓDIGO REFACTORIZADO ---
    }
    
    // --- ESTE ES EL NUEVO MÉTODO REFACTORIZADO ---
    /**
     * Método privado para cargar o recargar los datos de la base de datos en la JTable.
     * Es reutilizable y mantiene el constructor limpio.
     */
    private void cargarDatosEnTabla() {
        // 1. Instanciamos nuestro DAO
        // Usamos la Interfaz como tipo, pero creamos la Implementación.
        IFuncionarioDAO funcionarioDAO = new FuncionarioDAOImpl();
        
        // 2. Definimos los títulos de las columnas para nuestra tabla
        String[] titulos = {"Tipo ID", "Número ID", "Nombres", "Apellidos", "Estado Civil", "Sexo", "Teléfono"};
        
        // 3. Creamos un "modelo" para la tabla. No podemos añadir datos a la JTable directamente.
        // Hacemos que la tabla no sea editable por el usuario.
        DefaultTableModel tableModel = new DefaultTableModel(titulos, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // Todas las celdas no son editables
            }
        };

        // 4. Obtenemos la lista de funcionarios desde la base de datos
        // ¡Aquí es donde usamos nuestro DAO!
        List<Funcionario> listaFuncionarios = funcionarioDAO.obtenerTodos();
        
        // 5. Recorremos la lista y la añadimos al modelo de la tabla
        for (Funcionario f : listaFuncionarios) {
            Object[] fila = new Object[7]; // Un objeto por cada columna
            fila[0] = f.getTipoIdentificacion();
            fila[1] = f.getNumeroIdentificacion();
            fila[2] = f.getNombres();
            fila[3] = f.getApellidos();
            fila[4] = f.getEstadoCivil();
            fila[5] = f.getSexo();
            fila[6] = f.getTelefono();
            tableModel.addRow(fila); // Añadimos la fila al modelo
        }
        
        // 6. Finalmente, le decimos a nuestra tabla (tblFuncionarios) que use este modelo
        tblFuncionarios.setModel(tableModel);
    }
    // --- FIN DEL NUEVO MÉTODO ---
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        btnNuevo = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestión de Funcionarios");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncionarios);

        btnNuevo.setText("nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEditar.setText("editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNuevo)
                            .addComponent(btnEditar)
                            .addComponent(btnEliminar))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
       // 1. Creamos una instancia de nuestro formulario
        // El 'this' y 'true' lo hacen "modal" (bloquea la ventana principal)
        FormularioFuncionario formulario = new FormularioFuncionario(this, true);
        
        // 2. Hacemos visible el formulario
        formulario.setVisible(true);
        
        // 3. IMPORTANTE: Después de que el formulario se cierre,
        // necesitamos recargar la tabla para ver el nuevo funcionario.
        // Crearemos un método para esto.
        
        // (Por ahora, deja este espacio. Luego llamaremos a un método "cargarDatos()")
        cargarDatosEnTabla();
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // 1. Obtener la fila seleccionada
        int filaSeleccionada = tblFuncionarios.getSelectedRow();
        
        // 2. Validar si se seleccionó una fila
        if (filaSeleccionada == -1) {
            // Si es -1, no hay nada seleccionado
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario de la tabla para eliminar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return; // Detenemos la ejecución
        }
        
        // 3. Obtener los IDs (Clave Primaria) de la fila seleccionada
        // (Columna 0 = Tipo ID, Columna 1 = Número ID)
        // Obtenemos el valor de la celda y lo convertimos a String
        String tipoId = String.valueOf(tblFuncionarios.getValueAt(filaSeleccionada, 0));
        String numeroId = String.valueOf(tblFuncionarios.getValueAt(filaSeleccionada, 1));
        
        // 4. Pedir confirmación (¡MUY IMPORTANTE!)
        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(this, 
                "¿Está seguro de que desea eliminar al funcionario: " + numeroId + "?", 
                "Confirmar Eliminación", 
                javax.swing.JOptionPane.YES_NO_OPTION);
        
        // 5. Si el usuario presiona "Sí" (YES_OPTION es 0)
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            // 6. Llamar al DAO para eliminar
            IFuncionarioDAO funcionarioDAO = new FuncionarioDAOImpl();
            if (funcionarioDAO.eliminar(tipoId, numeroId)) {
                // Si el DAO devuelve true (éxito)
                javax.swing.JOptionPane.showMessageDialog(this, "Funcionario eliminado exitosamente.", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            } else {
                // Si el DAO devuelve false (error)
                javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar el funcionario.", "Error de BD", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
            
            // 7. Refrescar la tabla (pase lo que pase, para mostrar el estado actual)
            cargarDatosEnTabla();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
      // 1. Obtener la fila seleccionada
        int filaSeleccionada = tblFuncionarios.getSelectedRow();
        
        // 2. Validar si se seleccionó una fila
        if (filaSeleccionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario de la tabla para editar.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 3. Obtener los IDs (Clave Primaria) de la fila seleccionada
        String tipoId = String.valueOf(tblFuncionarios.getValueAt(filaSeleccionada, 0));
        String numeroId = String.valueOf(tblFuncionarios.getValueAt(filaSeleccionada, 1));
        
        // 4. Obtener el objeto Funcionario COMPLETO usando el DAO
        IFuncionarioDAO funcionarioDAO = new FuncionarioDAOImpl();
        Funcionario funcionarioParaEditar = funcionarioDAO.obtenerPorId(tipoId, numeroId);
        
        // 5. Validar que el funcionario exista (por si acaso)
        if (funcionarioParaEditar == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "No se pudo encontrar el funcionario para editar.", "Error de Carga", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 6. Abrir el formulario usando el NUEVO constructor (el de editar)
        //    Le pasamos el funcionario que encontramos.
        FormularioFuncionario formulario = new FormularioFuncionario(this, true, funcionarioParaEditar);
        formulario.setVisible(true); // El código se pausa aquí
        
        // 7. Refrescar la tabla después de que el formulario se cierre
        cargarDatosEnTabla();
    }//GEN-LAST:event_btnEditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFuncionarios;
    // End of variables declaration//GEN-END:variables
}
